name: Deploy to ECS (Blue-Green)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Register New Task Definition
        run: |
          aws ecs register-task-definition \
            --family dev-strapi \
            --network-mode awsvpc \
            --requires-compatibilities FARGATE \
            --cpu "512" \
            --memory "1024" \
            --execution-role-arn arn:aws:iam::663959447043:role/ecsTaskExecutionRole \
            --container-definitions "[{
              \"name\":\"strapi\",
              \"image\":\"663959447043.dkr.ecr.ap-south-1.amazonaws.com/strapi-ecs:latest\",
              \"essential\":true,
              \"portMappings\":[{\"containerPort\":1337,\"hostPort\":1337}]
            }]"

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name dev-codedeploy \
            --deployment-group-name dev-dg \
            --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
            --revision file://revision.json